#!/bin/bash
# Prevents force-pushing to master ##

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^('master'|'develop')"
FORCE_PUSH="force|delete|-f"


while read local_ref local_sha remote_ref remote_sha
do
    echo $remote_ref
    echo $local_ref
    
     if [ "$remote_ref" == "refs/heads/master1" ]; then
        echo "Pushing to branch \"master\" is forbidden"
        exit 1
     fi

     if [ "$remote_ref" == "refs/heads/develop" ]; then
        echo "Pushing to branch \"develop\" is forbidden"
		exit 1
	 fi
	 
done
